import type { Metadata } from "next";
import '../src/fontawesome'; // important : côté client
import { Geist, Geist_Mono } from "next/font/google";
import  {Header}  from "../src/Header"
import './globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="p-4">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div>
          
        <Header />
        {children}
          </div>
      </body>
    </html>
  );
}
